module.exports = {
  content: ['./*.php', './includes/*.php', './js/*.js', './css/*.css'],
  css: [
    './css/main.css',
    './css/pages.css',
    './css/mobile.css',
    './css/font.css',
    './css/fancybox.css',
    './css/unified-styles.css',
  ],
  output: './css/optimized/',
  safelist: [
    // Сохраняем важные классы, которые могут добавляться динамически
    'active',
    'hover',
    'focus',
    'disabled',
    'swiper-button-disabled',
    'swiper-pagination-bullet-active',
    'photo-modal.active',
    'filter-btn.active',
    'review-slide--text',
    'review-slide--photo',
    'review-slide--video',
    'phone-screenshot',
    // Сохраняем все классы с префиксами
    /^md-/,
    /^services-/,
    /^about-/,
    /^reviews-/,
    /^prices-/,
    /^contact-/,
    /^hero-/,
    /^benefit-/,
    /^service-/,
    /^cta-/,
    /^footer-/,
    /^header-/,
    /^nav-/,
    /^btn-/,
    /^form-/,
    /^modal-/,
    /^popup-/,
    /^swiper-/,
    /^fancybox-/,
    // Сохраняем утилитарные классы
    /^wrapper$/,
    /^container$/,
    /^grid$/,
    /^flex$/,
    /^text-/,
    /^bg-/,
    /^border-/,
    /^shadow-/,
    /^rounded-/,
    /^p-/,
    /^m-/,
    /^w-/,
    /^h-/,
    /^opacity-/,
    /^z-/,
    /^relative$/,
    /^absolute$/,
    /^fixed$/,
    /^block$/,
    /^inline$/,
    /^inline-block$/,
    /^hidden$/,
    /^visible$/,
    /^overflow-/,
    /^cursor-/,
    /^pointer-events-/,
    /^user-select-/,
    /^transition-/,
    /^transform-/,
    /^scale-/,
    /^rotate-/,
    /^translate-/,
    /^skew-/,
    /^filter-/,
    /^backdrop-/,
    /^blur-/,
    /^brightness-/,
    /^contrast-/,
    /^grayscale-/,
    /^hue-rotate-/,
    /^invert-/,
    /^saturate-/,
    /^sepia-/,
  ],
  defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
  fontFace: true,
  keyframes: true,
  variables: true,
  rejected: true,
}
