services:
  - type: worker
    name: ai-article-worker
    env: python
    plan: free
    buildCommand: 'pip install -r requirements.txt'
    startCommand: 'python3 ai_processor.py'
    envVars:
      - key: API_URL
        value: https://cherkas-therapy.ru/api
      - key: OPENAI_API_KEY
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: RUN_ONCE
        value: '0'

cronJobs:
  - name: ai-article-cron
    schedule: '*/10 * * * *' # каждые 10 минут
    command: 'python3 ai_processor.py'
    envVars:
      - key: API_URL
        value: https://cherkas-therapy.ru/api
      - key: OPENAI_API_KEY
        sync: false
      - key: UNSPLASH_ACCESS_KEY
        sync: false
      - key: RUN_ONCE
        value: '1'
