name: Quick Article Generation Test

on:
  # Ручной запуск
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode (demo articles)'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  generate-articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create environment file
        run: |
          cat > .env << EOF
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          UNSPLASH_ACCESS_KEY=${{ secrets.UNSPLASH_ACCESS_KEY }}
          MAX_ARTICLES_PER_DAY=1
          MIN_WORD_COUNT=5000
          MAX_WORD_COUNT=8000
          ANALYSIS_MODEL=gpt-3.5-turbo
          WRITING_MODEL=gpt-3.5-turbo
          USE_GPT4_FOR_COMPLEX=false
          LOG_LEVEL=INFO
          EOF

      - name: Run offline tests
        run: |
          python test_offline.py

      - name: Run publication test
        run: |
          python test_publication.py

      - name: Run simple cycle (demo articles)
        if: ${{ github.event.inputs.test_mode == 'true' }}
        run: |
          python run_simple_cycle.py

      - name: Run full AI processor
        if: ${{ github.event.inputs.test_mode == 'false' }}
        run: |
          python new_ai_processor.py

      - name: Upload results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results-${{ github.run_number }}
          path: |
            *.json
            *.log
            test_*.log
          retention-days: 7

      - name: Create summary
        if: always()
        run: |
          echo "## 🧪 Quick Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Test Mode:** ${{ github.event.inputs.test_mode }}" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** $(date '+%Y-%m-%d %H:%M UTC')" >> $GITHUB_STEP_SUMMARY
          echo "**Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -f "test_cycle.log" ]; then
            echo "### 📋 Test Logs" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            tail -10 test_cycle.log >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi
